print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")
print("powoli mam dosyć")

